src/mario/mod.rs, src/wario/mod.rs
[plugin.zip](https://github.com/chrispo-git/ult-s/files/9480741/plugin.zip)
resolves #2
=> Side Special Jump Cancel Fix

romfs/fighter/common/param/fighter_param.prcxml, src/ridley/mod.rs
Sideb grab movement speed reduced
Sideb angle increased 75 -> 88
Initial dash increased 1.8 -> 1.97
Fair landing lag reduced 16 -> 13
Uair landing lag reduced 14 -> 11
=> Ridley move adjustments

romfs/fighter/common/param/fighter_param.prcxml, src/cloud/mod.rs
Nair landing lag 10 -> 9
Fair landing lag 14 -> 11
Uair landing lag 10 -> 9
Bair landing lag 11 -> 10
Cloud can now B-reverse limit charge
=> Cloud changes

src/captain/mod.rs
This gives Falcon jab 3 an electric effect on his knee
=> Electric effect on Jab 3

src/kirby/mod.rs
Kirby Dsmash no longer continues making sounds on hit
=> Kirby dsmash bugfix

src/chrom/mod.rs
Sideb is no longer Attack Cancellable
=> Chrom Sideb Nerf

src/pitb/mod.rs
Upb now has a late hit (7-9):
Damage 14 -> 11
Size 12 -> 8
=> Dark Pit Upb nerf

src/samus/mod.rs
Samus Dtilt can no longer be wavedashed out of
=> Samus Dtilt Wavedash Removal

src/brave/mod.rs
Hero Jab 1 and 2 do less bonus hitstun 7 -> 4
=> Hero Jab 1 and 2 Adjustments

src/lucina/mod.rs, src/marth/mod.rs
Marcina upb hitbox now matches the effect
=> Marcina Upb adjustment

src/koopa/mod.rs
Fireball damage 13 -> 19
Fireball BKB 47 -> 40
Fireball hitlag 1.0 -> 1.5
=> Bowser Fireball Buffs

romfs/fighter/common/param/common.prcxml
=> Ten Degree DI

src/common/command.rs
Incineroar Airdash speed reduced
=> Incineroar Airdash

src/mariod/mod.rs
=> Doc Up B Effects

src/koopajr/mod.rs
Bowser Jr. has lost triple jump
Bowser Jr. can now float
=> bowser jr float

src/roy/mod.rs
Ftilt FaF increased 33 -> 35
Ftilt sour hitbox altered:
Size 7.0 -> 6.2
Z Offset 25.0 -> 23.5
Dash Attack Startup increased 8 -> 10
Dash Attack Hitbox size reduced 5.0 -> 3.0
Dash Attack finisher angle increased 42 -> 60
=> Roy Adjustments

src/trail/mod.rs
Sora Thundaga is no longer reflectable
This is a bandaid fix to remove the Thundaga projectile nullify bug
Solves #136
=> Sora Thundaga Fix

src/metaknight/mod.rs
Dair angle altered 270/70 (Early/Late) -> 270/80
Dair now bounces on hit
Solves #5
=> Metaknight Dair

src/duckhunt/mod.rs
Duck Hunt Up Angled Ftilt Altered:
Bonus hitstun 5 -> 0
KBG 100 -> 85
=> Duck Hunt Uaftilt Nerf

src/purin/mod.rs
Dair autocancel frame reduced 47 -> 42
=> Jigglypuff Dair adjustment

src/pitb/mod.rs
You know how you set a ball up to be spiked in volleyball? Chrispo, alley-oop!
Ftilt and DA cancel into side b only on hit
Initial Hbox of up b size adjustment:
- Size: 12.0 > 8.0
- Z value offset: 0.0 > 6.0
=> Dark Pit: The Dark Flash

src/captain/mod.rs
=> Captain falcon

src/common/command.rs
Motion Input max leniency frames increased 30 -> 35
Motion Inputs now require pressing A+B
=> Motion Input Update

src/common/landing.rs, src/common/wavedash.rs, src/util/mod.rs
Wavedashing with the fullhop button now behaves identically to with the shorthop button
LLPCing Wavelands has been made harder
Shielddrop has been added
=> Wavedash and other adjustments

src/ryu/mod.rs
Kirby can now correctly shoot out hadoukens!
=> Ryu Copy Ability Bug

src/common/projectile_invuln.rs, src/miiswordsman/mod.rs
Just some small changes
- Fair 3 has a reduced angle and adjusted KB
BKB: 55 > 50
KBG: 130 > 135
Angle: 50 > 35
- Dthrow got increased KBG
KBG: 100 > 110
- Gale stab no longer charges
- Power thrust now has projectile invulnerability
=> miiswordsman

src/kamui/mod.rs
Corrin bthrow knockback reverted to vanilla
=> Corrin Bthrow knockback revert

romfs/fighter/pickel/param/vl.prcxml
Steve mining speed buffed:
Hand 2.86 -> 2.5
Wood 1.43 -> 1.25
Stone 1.35 -> 1.1875
Iron 1.29 -> 1.125
Gold 1.07 -> 0.93
Diamond 1.21 -> 1.0625
=> Steve Mining Changes

scripts/build_diff.py
adds build_diff.py
Usage:
1. Open py file
2. select new Ultimate S Acropolis and Stages folders, and then select old versions
3. check releases, zipped version of all the changed files
=> Build Diff

src/common/command.rs
=> Plant Command Input Removal

src/common/command.rs
=> Mario Command Input removal

src/kirby/mod.rs
Ftilt startup increased 6 -> 11
=> Kirby Ftilt Nerf

romfs/fighter/common/param/common.prcxml
Parry window reverted to vanilla
=> Parry window revert

src/captain/mod.rs
(Title Credit to EllaOW)
https://pastebin.com/cU3h7WDb
=> Captain Falcon, Avatar of Speed and Power

src/lib.rs
Should fix emulators going 2x speed
=> Fix Emulator latency

src/ganon/mod.rs
Fair startup: 10 > 14
Fair Damage: 10/11 > 12/13
Fair early ac: 1-9 > 1-10
Usmash Startup: 14 > 11
Usmash damage: 19 > 15
Jab startup: 6 > 7
=> Ganon cleanup

src/lib.rs
Stage config plugin added to dependency checker
=> Stage config plugin added to dependency checker

Cargo.toml, src/lib.rs
=> Revert "Dependencies Checker"

src/miigunner/mod.rs
First PR of 3.1.2 and it's a fucking bug fix lmao.
literally just had dsmash's effect come out too late and in the wrong spacing.
=> Gunner Clean up

romfs/fighter/koopa/param/vl.prcxml
=> Bowser Fireball

src/murabito/acmd/throws.rs
villy fthrow script erroneously applied to sheik. Fixed!
=> Sheik Fthrow fix

src/falco/acmd/aerials.rs
Fair landing hitbox reimplemented
nair BKB reduced: 20 > 15
Falco Bair startup increased: 5 > 7
=> Falco Changes

src/miigunner/frame.rs
=> Mii gunner LC fix

src/samusd/acmd/specials.rs, src/samusd/frame.rs
Fixes bug where you could fire off 2 dark samus sidebs in quick succession
=> Dark samus sideb bugfix

romfs/fighter/common/param/fighter_param.prcxml, src/purin/acmd/ground.rs
DA extra momentum removed: 0.6 > 0
weight decreased: 75 > 72
=> Jigglypuff nerfs

src/chrom/acmd/specials.rs, src/chrom/acmd/tilts.rs, src/chrom/frame.rs
Side special dash active frames increased 10-15 -> 10-17
Daftilt altered:
Angle increased 80 -> 94
BKB reduced 85 -> 65
KBG increased 40 -> 60
FaF fixed
=> Chrom Sideb and daftilt buffs

changelog/how2changelog.md, changelog/mario.md
=> Changelog branch

src/controls/controls_2.rs, src/controls/mod.rs, src/lib.rs
=> 13.0.2 offset fix

changelog/gnw.md, changelog/ike.md, changelog/sora.md, changelog/wiifit.md, scripts/statistics.py
=> Data doc extend

src/koopajr/acmd/throws.rs
Bowser Jr. Dthrow now puts into a techchase situation rather than lay status
=> Bowser Jr knockdown Throw

src/snake/status.rs
Snake can no longer walk while holding the opponent, and his throw works as normal.
=> Snake Grab walking removal

src/brave/acmd/tilts.rs, src/common/projectile_invuln.rs
https://pastebin.com/1EczWAvu
Ftilt 1 no longer has invincibility. The shield has projectile nullification.
=> Hero Tweaks

src/reflet/acmd/aerials.rs, src/reflet/acmd/specials.rs
https://pastebin.com/Ns5FEVra
Bronze Nair angle: 30 > 80
Grima aerial up b vertical travel distance: 0.8 > 1.0
=> Robin tweaks

src/metaknight/acmd/specials.rs, src/metaknight/status.rs
Metaknight neutralb is now a multihit:
Damage altered 12/8 (Early/Late) > 0.6/3 (Multi/Final)
Angle increased 361 > 70
BKB reduced 90 > 55
KBG increased 100 > 170
=> Metaknight Multihit Tornado

romfs/fighter/common/param/fighter_param.prcxml
Dark Samus has had zair returned
=> Dark Samus Zair 

src/murabito/frame.rs, src/murabito/status.rs
Villager and Toad Neutral Specials no longer moonjump after a ledgejump
=> Villager Neutral Special Bugfix

romfs/fighter/sonic/param/vl.prcxml
Homing attack bounces less on hit
=> Sonic homing attack on hit

src/common/landing.rs
LLPC no longer applies to wavedashes and wavelands
=> LLPC change

scripts/c00clone.py
you can now provide c00clone.py with a characters name to automatically clone their motion folders together c00-c07
=> C00clone update

changelog/fox.md, romfs/fighter/common/param/fighter_param.prcxml
=> Fox Nair LL Reduction

romfs/fighter/common/param/fighter_param.prcxml, src/richter/acmd/specials.rs
Dash speed increased: 1.92 > 1.98
Air accel max increased: 0.02 > 0.05
Knife startup reduced: 17 > 13
=> Richter buffs

src/common/mod.rs, src/common/training.rs, src/cpu/mod.rs, src/util/mod.rs
Dtaunt in training mode also toggles on random DI and buffering airdodge/shield out of hitstun.
Left Taunt during this mode forces DI in, Right Taunt forces DI out, and Up Taunt resets to random DI.
=> Training Mode Changes

src/pichu/acmd/aerials.rs, src/pichu/frame.rs
Fixed: dair not applying correct momentum out of hitstun
Fixed: using up b after doing grounded jump and double jump would give pichu two extra jumps
=> Pichu bug fixes

src/common/movement.rs
=> perfect pivot fix

changelog/pichu.md, src/pichu/acmd/specials.rs
=> Pichu downb nerf

src/element/elight/acmd/tilts.rs
=> Mythra Nair Fix

src/sandbag/acmd/specials.rs
Disc damage reduced 5 -> 4
Disc KBG increased 40 -> 60
=> Sandbag Neutralb nerf

src/rayman/acmd/specials.rs, src/rayman/mod.rs
Changed probability of the below voice calls:
Side B: 100% > 70%
Double Jump: 1/6 > 1/4
=> Rayman vc probability

changelog/masked.md, src/masked/acmd/throws.rs
Dthrow damage reduced 18% -> 4%
=> Masked Man Dthrow Nerf

src/common/mod.rs, src/common/training.rs, src/util/mod.rs
Fixes pressing dtaunt to enable and disable training mode changes
Fixes airdodge out of hitstun for electric moves
Introduces random ledge options:
-  Ledgedrop DJ, Neutral Getup, Ledgeroll, Ledgejump, Ledge Attack, Wait
- Followups to the ledge options: Aerial/Grounded Move, Shield/Airdodge, Nothing)
=> Training mode fixes

Ultimate S Setup Tool.py, readme.txt, scripts/build_dev.py, src/lib.rs
Ultimate S Setup Tool updated:
- Now able to check for new updates from ultimate S
- Now able to automatically set up your SD card for the mod and transfer to it (either by FTP or to a specific folder)
- Fixed bugs relating to aegis and pokémon trainer
=> Update setup tool more

src/palutena/acmd/aerials.rs
=> Palutena Fair adjustment

src/dedede/acmd/specials.rs, src/dedede/frame.rs, src/dedede/mod.rs
King dededee can hit his own gordos (they can hit dedede after being hit)
=> Dedede Gordo change

src/brave/frame.rs
Hero Ftilt no longer cancels into multiple things
=> Hero Ftilt reversion

src/mewtwo/acmd/aerials.rs, src/mewtwo/acmd/tilts.rs
Nair now always hits forwards
Tail invulnerability has been adjusted:
Uair tail invuln period adjusted 3-35 -> 7-17
Ftilt tail invuln period adjusted 0 -> 7-14
Utilt tail invuln period adjusted 0 -> 5-16
Dtilt tail invuln period adjusted 0 -> 3-10
=> Mewtwo Buffs

src/sandbag/acmd/specials.rs
Now Reflectable! (Why wasnt it)
=> Sandbag Disc Fix

src/pitb/frame.rs
=> Dark Pit Upb bugfix

romfs/fighter/samus/param/vl.prcxml, src/samus/acmd/tilts.rs, src/samus/frame.rs
Up b distance increase removed
Up tilt invincibility removed
Down tilt only cancels on hit now
=> Samus nerfs

Ultimate S Setup Tool.py
Removes arena latency plugin from install list
Removed deprecated Github library
Setup should now work just fine again
=> Fix Ultimate S Setup Tool

src/bomberman/status.rs
Added flashing effect as an indication when neutral special is fully charged
=> Bomberman flash

src/common/jab.rs
Jab cancels can no longer cancel into smash attacks (this was a long time coming)
=> Jab Cancel Reductions

src/bomberman/frame.rs
Added hurtbox to Bombermans head
=> Bomberman hurtbox

src/peach/frame.rs
Peach no longer slides when transitioning from air to ground with neutral special
=> Peach Neutral Special bugfix

src/common/movement.rs, src/util/mod.rs
Moonwalking added to the game
Dash shield adjusted:
Now able to dash shield without being forced into run (odd vanilla behaviour).
=> Dash Changes

src/common/movement.rs, src/util/mod.rs
Fixed buffered aerial item throws
Fixed fullhopping out of shield
=> Buffer adjustments

src/toad/frame.rs
Dive should be able to be cancelled with the c-stick now
=> Toad Sideb fix

src/falco/frame.rs
=> Falco Shine Momentum

src/rosetta/status.rs
Rosalina Down Special invisibility bug fixed
Solves #137
=> Rosalina DownB Bug Fix

src/bomberman/status.rs
Bomberman Neutral Special no longer floats in the air if transitioning from ground to air while charging.
Solves #571.
=> Bomberman Neutral Special Bugfix

romfs/config_param.toml
Down Special max vertical distance increased 0.85 -> 1.5
=> Luigi Down Special

src/donkey/frame.rs
=> Donkey Kong Upb Adjustment

src/jack/acmd/specials.rs
Fixes Joker Voicelines playing incorrectly during Gun
=> Joker Voiceline Fix

src/common/wavedash.rs, src/util/mod.rs
Fixes breaking bugs in Ultimate S Lite
=> Ultimate S Lite Bugfix
